### ISSUE TITLE
is their any method available for EDITING the existing node

### ISSUE THREAD

**Issue by praveenhariyala** [inspirsea/tree-ngx#1]
in the API their is no edit method available

**Comment by inspirsea** [comment]
I will look into this, seems like a reasonable feature to implement.

**Comment by inspirsea** [comment]
Added 2 methods for editing name and item of a node.

https://github.com/inspirsea/tree-ngx/commit/6ec67dfc30110caec484ca23fdfaa9350ab8fcc3

Another way to change a current node would be to override the default template.

Something like
``<ng-template #nodeNameTemplate let-node="node" let-context="context">
      <span [class.active]="context.active">{{node.name}} id: {{node.id}}</span>
      <input type="text" [(ngModel)]="node.name">
</ng-template>``

where "node" is the nodeItem.

See http://emilsunesson.com/code/tree-ngx-custom-template
