### ISSUE TITLE
collapseAll() doesn't work in ngAfterViewInit.

### ISSUE THREAD

**Issue by AntonDr** [inspirsea/tree-ngx#10]
How i can collapse tree after navigating to page with tree?

**Comment by inspirsea** [comment]
Hi, you should be able to use the expanded property to determine the initial value of your nodes. See NodeItem

http://emilsunesson.com/docs/tree-ngx/tree-ngx-api

Determines if the node is expanded from start. Only nodes that have children. Default is true
expanded?: boolean
