### ISSUE TITLE
Hi , I am not able to use selectedItem event 

### ISSUE THREAD

**Issue by vinayakshettar** [inspirsea/tree-ngx#11]
Hi I am using user library for angualar  12. I am not sure if it supports ...  When click on checkbox SelectedItem event fires.. but item value does not have selected item.
(1) [undefined]
0:undefined
[[Prototype]]:Object
length:1
[[Prototype]]:Array(0)

SelectedItem(item: any) {
    
    this.data.next([item.name]);
  }

<tree-ngx  #treeRef  [nodeItems]="nodeItems"  (selectedItems)="SelectedItem($event)" [options]="options" [callbacks]="treecallbacks">
</tree-ngx>

**Comment by inspirsea** [comment]
Hi i can't reproduce your problem can you provide a minimal code example or additional information.

**Comment by vinayakshettar** [comment]
Hello ,I found awork around .. Its working fine ..thank you

**Comment by Chandrakanta30** [comment]
//htm

  <tree-ngx  #treeRef
            [nodeItems]="controllersList" 
            (selectedItems)="SelectedItemEvent($event)"
            [options]="options"
            >
            </tree-ngx>

//ts
SelectedItemEvent(event:any){
        console.log(event);

    }
    the selected items is not working not giving any outputs

**Comment by inspirsea** [comment]
Set
alwaysEmitSelected

**Comment by Chandrakanta30** [comment]
The function all values as undefined

**Comment by Chandrakanta30** [comment]
![Screenshot from 2023-06-19 16-55-38](https://github.com/inspirsea/tree-ngx/assets/43083370/745971ee-5da6-4319-a4a6-659a5c292655)

**Comment by Chandrakanta30** [comment]
after setting alwaysemitselected is always emmiting undefinded value
