### ISSUE TITLE
How to expand filtered nodes in the tree

### ISSUE THREAD

**Issue by vinayakshettar** [inspirsea/tree-ngx#13]

**Comment by inspirsea** [comment]
Unclear question, elaborate on what you are trying to achieve.

**Comment by vinayakshettar** [comment]
When i type in search string in the textbox and assign that string to [filter] attribute it filters the tree but .. tree does not highlight or show the inner matching node. it just shows the parent node. Initially i dont expand all the nodes.   manually we have to expand the node to see matching node. 
instead i wanted to have matching nodes should be shown

**Comment by inspirsea** [comment]
You should be able to the expand the parent nodes with expandById(id: string): void
