### ISSUE TITLE
where is style folder?)

### ISSUE THREAD

**Issue by vxp123** [inspirsea/tree-ngx#14]
An unhandled exception occurred: ENOENT: no such file or directory, lstat './node_modules/tree-ngx/style'
See "/tmp/ng-dBPUP5/angular-errors.log" for further details.

**Comment by inspirsea** [comment]
Hi the build pipelane was changed in the latest version. The style should now be imported as 
@import 'tree-ngx';

**Comment by vxp123** [comment]
Ok, ty.
Just need change version from ^4.1.0 to 4.1.0
