### ISSUE TITLE
Error importing styles

### ISSUE THREAD

**Issue by alexac7** [inspirsea/tree-ngx#15]
According to the documentation, @import 'tree-ngx' must be imported; but I get the error when compiling my project

HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
    ╷
56 │ @import '~tree-ngx';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

the bug with angular 14

**Comment by inspirsea** [comment]
Hi, the import should be 

@import 'tree-ngx'

Without the ~
