### ISSUE TITLE
Viewing tree shows all items even when not selected

### ISSUE THREAD

**Issue by jesscrees** [inspirsea/tree-ngx#2]
If I show the tree, without checkboxes, it will show all the options passed back even if they say `selected: false`. This makes it difficult to set up a page where the user can use the checkbox tree to set information and then click save and view only the saved information in the non-checkbox tree.

Is it possible to set this as an option that can be passed in to the tree component to change the view mode of it?

**Comment by inspirsea** [comment]
Hi, im not sure i understand your issue. Do you want the nodes to be removed when they get deselected?

I think a better solution to your problem would be to use 2 instances of the tree and switch between them depending on your application state. 

You could use a NoSelect tree when in view mode to disable interactions.

Have i understood your problem correctly?

**Comment by jesscrees** [comment]
Hi there!

I don't want to change the nodes in the tree at all. The checkbox view is fine as is, it's the non-checkbox view that I'd like to be a little different.

I'm already switching between the two types of tree but I thought it would be nice if the non-checkbox view had the option as to whether it could show all the nodes or only the nodes that are `selected: true`.

I'm already making separate api calls to get the data for the different views so I can work around this but I thought it would be a nice addition to the component.

**Comment by inspirsea** [comment]
This is potentially a common use-case, i created a new mode for this TreeMode.HideSelected
You should now be able to switch between different options like MultiSelect and HideSelected.
