### ISSUE TITLE
checkBox disable when the json return null children

### ISSUE THREAD

**Issue by myalsailamy** [inspirsea/tree-ngx#4]
[
      {
        'id': 1,
        'name': 'Node1',
        'item': 1,
        'children': [
          {
            'id': 2,
            'name': 'Node1-A',
            'item': 2,
            'children': [
              {
                'id': 5,
                'name': 'Node1-A-1',
                'item': 5,
                'children': []
              },
              {
                'id': 6,
                'name': 'Node1-A-2',
                'item': 6,
                'children': []
              },
              {
                'id': 7,
                'name': 'Node1-A-3',
                'item': 7,
                'children': []
              }
            ]
          },
          {
            'id': 3,
            'name': 'Node1-B',
            'item': 3,
            'children': []
          },
          {
            'id': 4,
            'name': 'Node1-C',
            'item': 4,
            'children': []
          }
        ]
      }
    ]

when i put this json some of checkbox disabled , and multiselect not work.
but when i deleted null 'children': [] from json it's work good and all checkbox work well , 
would you fix this bug to ignore null children

https://i.ibb.co/rwZS8bG/Untitled.png

**Comment by CarnageAlpha** [comment]
Hi sorry for the late reply. In this scenario everything should be disabled as you have no leaves in the tree, only leaves can hold values. There seems to be a bug where not all the checkboxes are disabled tho.

I might consider adding an option where parents can hold values, feel free to submit a feature request.

**Comment by inspirsea** [comment]
Hi sorry for the late reply. In this scenario everything should be disabled as you have no leaves in the tree, only leaves can hold values. There seems to be a bug where not all the checkboxes are disabled tho.

I might consider adding an option where parents can hold values, feel free to submit a feature request.

**Comment by inspirsea** [comment]
The behaviour har been changed in 3.0.0 and should now feel more streamlined and intuitive.
