### ISSUE TITLE
Is there any way to find node in the tree

### ISSUE THREAD

**Issue by myalsailamy** [inspirsea/tree-ngx#6]
hi ,,

Is there any way to find node by Id as another functions :
deleteById(id: string)
editNameById(id: string, name: string)
editItemById(id: string, item: any)

I am trying to change [checked value] programmatically by id.

**Comment by myalsailamy** [comment]
thanks, i found your private function and i use it like this : 

```
import { Component, OnInit, ViewChild } from '@angular/core';
import { TreeMode, NodeItem, TreeOptions, TreeNgxComponent } from 'tree-ngx';
```

`
@ViewChild('firstTreeRef') TreeRef: TreeNgxComponent;
`

```
  findById = function (state, arg) {
    return state.nodeItem.id === arg;
  };

  getNodeItem = function (nodeStates, arg, compare) {
    var result = nodeStates.find(function (it) { return compare(it, arg); });
    if (result) {
        return result;
    }
    else {
        for (var _i = 0, nodeStates_3 = nodeStates; _i < nodeStates_3.length; _i++) {
            var state = nodeStates_3[_i];
            result = this.getNodeItem(state.children, arg, compare);
            if (result) {
                return result;
            }
        }
    }
    return result;
  };

```

how to use : 

```
      var result  = this.getNodeItem(this.TreeRef.treeService.treeState , 13 , this.findById );
      this.TreeRef.treeService.checkBoxClick(result);
      console.log(result);
```

**Comment by inspirsea** [comment]
I´m happy you could solve it. 
However this should be a part of the API.
I will make sure to add it. Thank you for the feedback.

**Comment by myalsailamy** [comment]
There is some of feature I hope you will add it into the next version.

when  i collapse all tree Using this function :

`this.TreeRef.collapseAll();`

and check child node programmatically by Using this function :

`this.TreeRef.treeService.checkBoxClick(result);`

I need to expand parents  for specific child node,  so I made this function :

```
  expandedAllParents(nodeStates) {
    if (nodeStates.parent) {
      nodeStates.parent.expanded = true;
      this.expandedAllParents(nodeStates.parent);
    }
  }
```

i think you can make it better by usings id of node.

Aonther thing when i use  clean() method its work with selected childern  but parents  still checked.

so i use this fuction to clean all checkbox from nodes 

```
  uncheckedAllChildrenNode(nodeStates) {
    nodeStates.selected = false;
    nodeStates.selectedState = 1;
    for (let _i = 0, nodeStates_3 = nodeStates; _i < nodeStates.length; _i++) {
        const state = nodeStates_3[_i];
        state.selected = false;
        state.selectedState = 1; // NodeSelectedState.unChecked
        this.uncheckedAllChildrenNode(state.children);
    }
  }
```

use this function like this :

`this.uncheckedAllChildrenNode(this.TreeRef.treeService.treeState);`
